export const interactionsData = [
  {
    id: 1,
    isSelected: true,
    isCurrentWeek: true,
    name: "Jacob Jones (3)",
    mobile: "+1 123456789",
    timeAgo: "5m",
  },
  {
    id: 2,
    isSelected: false,
    isCurrentWeek: true,
    name: "Jacob Jones (3)",
    mobile: "+1 123456789",
    timeAgo: "5m",
  },
  {
    id: 3,
    isSelected: false,
    isCurrentWeek: true,
    name: "Jacob Jones (3)",
    mobile: "+1 123456789",
    timeAgo: "5m",
  },
  {
    id: 4,
    isSelected: false,
    isCurrentWeek: false,
    name: "Jacob Jones (3)",
    mobile: "+1 123456789",
    timeAgo: "5m",
  },
  {
    id: 5,
    isSelected: false,
    isCurrentWeek: false,
    name: "Jacob Jones (3)",
    mobile: "+1 123456789",
    timeAgo: "5m",
  },
];
