export const brandingOption = [
  { value: "flow-ai", label: "Flow AI" },
  { value: "no-branding", label: "No branding" },
];
export const languageOptions = [
  { value: "english", label: "English", key: "en" },
  { value: "french", label: "French", key: "fr" },
  { value: "spanish", label: "Spanish", key: "sp" },
];
export const fontFamilyList = [
  { label: "Arial", value: "Arial" },
  { label: "Poppins", value: "Poppins" },
  { label: "Rancho", value: "Rancho" },
  { label: "Lustria", value: "Lustria" },
  { label: "Mr Dafoe", value: "Mr Dafoe" },
  { label: "Spinnaker", value: "Spinnaker" },
  { label: "Unna", value: "Unna" },
  { label: "Prosto One", value: "Prosto One" },
  { label: "Fredericka the Great", value: "Fredericka the Great" },
  { label: "Maven Pro", value: "Maven Pro" },
  { label: "Noto Sans TC", value: "Noto Sans TC" },
  { label: "Permanent Marker", value: "Permanent Marker" },
  { label: "Gloria Hallelujah", value: "Gloria Hallelujah" },
  { label: "Catamaran", value: "Catamaran" },
  { label: "Overpass", value: "Overpass" },
  { label: "Fira Sans Condensed", value: "Fira Sans Condensed" },
  { label: "Francois One", value: "Francois One" },
  { label: "Rajdhani", value: "Rajdhani" },
  { label: "CINZEL", value: "Cinzel" },
  { label: "Domine", value: "Domine" },
  { label: "Crete Round", value: "Crete Round" },
  { label: "Vollkorn", value: "Vollkorn" },
  { label: "Rokkitt", value: "Rokkitt" },
  { label: "Cantarell", value: "Cantarell" },
  { label: "Cuprum", value: "Cuprum" },
  { label: "Satisfy", value: "Satisfy" },
  { label: "PT Sans Caption", value: "PT Sans Caption" },
  { label: "ABeeZee", value: "ABeeZee" },
  { label: "Prompt", value: "Prompt" },
  { label: "Alegreya", value: "Alegreya" },
  { label: "Ropa Sans", value: "Ropa Sans" },
  { label: "Courgette", value: "Courgette" },
  { label: "News Cycle", value: "News Cycle" },
  { label: "Cardo", value: "Cardo" },
  { label: "Amiri", value: "Amiri" },
  { label: "Patua One", value: "Patua One" },
];
